project:
  type: website

website:
  title: "Draft Neighborhood Change Types"
  navbar:
    search: false
    pinned: true
    left:
      - text: "Home"
        file: index.html
      - text: "Displacement Due to Price Pressures"
        file: create_outcomes_pt1.html
      - text: "Population Loss Due to Economic Disinvestment & Inclusive Growth"
        file: create_outcomes_pt2.html

format:
  html:
    grid:
      sidebar-width: 300px
      body-width: 900px
      margin-width: 100px
      gutter-width: 1.5rem